import React from "react";
import background from "../images/background.png";
function Homepage() {
  return (
    <>
      <div className=" homepage pt-10 max-sm:h-screen">
        <div className=" pt-20">
          <h1 className=" text-center font-bold text-4xl font-sans text-slate-600">
            Welcome to messaging app{" "}
          </h1>
        </div>
        <div className=" max-sm:block flex justify-between w-1/2 mx-auto pt-20 cursor-pointer">
          <a href="/login-admin">
            <div className=" max-sm:py-4 max-sm:px-0 max-sm:text-center rounded-md bg-slate-600 py-10 px-12">
              <h1 className=" font-semibold text-white">Continue as Admin</h1>
            </div>
          </a>
          <a href="/login-prefect">
            <div className=" max-sm:py-4 max-sm:mt-2 max-sm:px-0 max-sm:text-center rounded-md bg-slate-600 py-10 px-12">
              <h1 className=" font-semibold text-white">Continue as Prefect</h1>
            </div>
          </a>
        </div>
        <div></div>
        <div className=" w-5/6 pt-6">
          <h1 className=" float-right font-semibold">
            Generated by <span className=" text-orange-600">Bobodev</span>
          </h1>
        </div>
      </div>
    </>
  );
}

export default Homepage;
